### ISSUE TITLE
Combinar todo

### ISSUE THREAD

**Issue by livan23l** [livan23l/deseos2025#29]
Ahora que ya tenemos los componentes individuales es hora de crear el sitio web.

- [x] Trabajarás con los archivos `index.html` (ya está creado), `generador-carta.html` (necesitas crearlo) y `cuenta.html` (necesitas crearlo).
- [x] Agrega el _header_ en los tres archivos y modifica las rutas del mismo para que apunten de la siguiente manera:
    - [x]  El texto principal apuntará al archivo `index.html`
    - [x] Los enlaces apuntarán a donde dicen redirigir
- [x] En el archivo `index.html` deberás poner:
    - [x] El header
    - [x] El carrusel de imágenes (no te preocupes por las imágenes, luego se cambiarán)
    - [x] La sección de nosotros (cambia también los enlaces que aparecen ahí)
- [x] `generador-carta.html` debe tener únicamente el header y el formulario
- [x] `contador.html` debe tener únicamente el header y el contador de la cuenta regresiva

- [x] Debes asegurarte de que todo se vea correctamente. Corrige distancias entre un elemento y otro (margin) y todo lo necesario
- [x] Todas las secciones que no sean el header las pondrás dentro de un main con la clase `main`
- [x] A la clase `main` que acabas de crear debes darle un padding en el eje x (el que consideres conveniente)
- [x] Debes darle un color de fondo en el `body` (de preferencia un gradiente lineal, busca que quede lo mejor posible)
- [x] Corrige y cambia los diseños que veas necesarios
- [x] Una vez todo quede en los 3 archivos mencionados borra el resto (los componentes individuales)
